version: '3'
services:
  php-api:
    build: .
    ports:
      - "8080:80"

  mysql:
    image: mysql:8.0.32
    restart: always
    ports:
      - 3306:3306
    command:
      [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
      ]
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: "detikcom_123!@#"

volumes:
  db:
    driver: local
